### ISSUE TITLE
Implement location services

### ISSUE THREAD

**Issue by mscosti** [Robrowski/GeoSnap#3]
Whenever the app is open in main activity we should have location on so we pull our latitude and longitude easily when we take a picture, and so we can package it up to be sent to geocloud

**Comment by Robrowski** [comment]
Location is as available as its going to get. (On service starts, it requests the last location out of the Google API, then requests updates). Done.


BUT: If location (and internet i think) are turned off, no location ever... new issue for putting a UI that tells user internet/location are turned off?

**Comment by Robrowski** [comment]
Warning pops up now! But only when the MainActivity's "onStart" is called. Good enough for now.
